require('settings.plugin.nvim_cmp')
require('settings.plugin.nvim_lsp_installer')
require('settings.plugin.nvim_lsp_config')
require('settings.plugin.colorscheme')
require('settings.plugin.telescope')
require('settings.plugin.lualine')
require('settings.plugin.neoscroll')
require('settings.plugin.kommentry')
require('settings.plugin.dashboard')
require('settings.plugin.indent')
require('settings.plugin.autopairs')
require('settings.plugin.snippets')
require('settings.plugin.formatter')
require('settings.plugin.barbar')
require('settings.plugin.rainbow')
require('settings.plugin.gitsigns')
require('settings.plugin.nvim_tree')
require('settings.plugin.nvim_metals')
require('settings.plugin.presence')
-- require('settings.plugin.lsputils')

-- Initialize Plugins
require('nvim-ts-autotag').setup()
