require('settings.plugin.compe')
require('settings.plugin.lsp-install')
require('settings.plugin.nvim-lsp')
require('settings.plugin.colorscheme')
require('settings.plugin.telescope')
require('settings.plugin.galaxyline')
require('settings.plugin.neoscroll')
require('settings.plugin.kommentry')
require('settings.plugin.gitsigns')
require('settings.plugin.dashboard')
require('settings.plugin.indent')
require('settings.plugin.autopairs')
require('settings.plugin.snippets')
require('settings.plugin.formatter')
require('settings.plugin.barbar')
require('settings.plugin.rainbow')

-- Initialize Plugins
require('nvim-ts-autotag').setup()
